import axios from "axios";
import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Web tutorials",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const response = await axios.get("http://localhost:9999/topics")
  const topics = response.data

  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map(topic => (
            <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          ))}
        </ol>
        {children}
        <li><Link href="/create">Create</Link></li>
        <li><Link href="/update">Update</Link></li>
        <li><button>Delete</button></li>
      </body>
    </html>
  );
}
